spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/grocery?allowMultiQueries=true&createDatabaseIfNotExist=true
    username:
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  liquibase:
    enabled: true
    drop-first: false
    default-schema: grocery
    change-log: classpath:changelog/db.changelog-master.yaml
liquibase:
  liquibaseTablespaceName: grocery