CREATE TABLE GROCERY_INVENTORY (
  ID int NOT NULL AUTO_INCREMENT,
  GROCERY_ITEM varchar(50) DEFAULT NULL,
  PRICE int NOT NULL,
  QUANTITY int DEFAULT NULL,
  CREATED_BY varchar(25) DEFAULT NULL,
  CREATED_ON datetime DEFAULT NULL,
  MODIFIED_BY varchar(25) DEFAULT NULL,
  MODIFIED_ON datetime DEFAULT NULL ON UPDATE NOW(),
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;